-- 'public.notes' table and its policies was created using Supabase Studio.
-- SQLs extracted from the Supabase console

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.
CREATE TABLE public.notes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  content text,
  user_id uuid,
  CONSTRAINT notes_pkey PRIMARY KEY (id),
  CONSTRAINT notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);

----- Following SQLs were generated by chatGPT

-- 1) Optional: enable pgcrypto (for gen_random_uuid). Skip if you already use uuid functions.
create extension if not exists pgcrypto;

-- 2) Create the todos table (if you already created it, skip or adjust)
create table if not exists public.todos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  task_text text not null,
  completed boolean not null default false,
  inserted_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3) Create the trigger function that sets updated_at
create or replace function public.trigger_set_timestamp()
returns trigger
language plpgsql
as $$
begin
  -- set the updated_at column to the current timestamp
  new.updated_at := now();
  return new;
end;
$$;

-- 4) Create the trigger that calls the function before each UPDATE
drop trigger if exists set_timestamp on public.todos;
create trigger set_timestamp
before update on public.todos
for each row
execute procedure public.trigger_set_timestamp();

alter table todos enable row level security;

create policy "Users can view their own todos"
  on todos for select
  using (auth.uid() = user_id);

create policy "Users can insert their own todos"
  on todos for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own todos"
  on todos for update
  using (auth.uid() = user_id);

create policy "Users can delete their own todos"
  on todos for delete
  using (auth.uid() = user_id);
